app_id: 65e44c1e-4f63-4abf-ab9e-d532f6b8a421
publisher: RtuGeek
publisher_url: https://haihaihai.vip
display_name: 电子木鱼
setup_icon_file: C:\Users\neo\Desktop\workspace\wooden_fish\windows\runner\resources\app_icon.ico
locales:
  - zh